apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-$USER
  namespace: decice
  labels:
    app: collector-$USER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector-$USER
  template:
    metadata:
      labels:
        app: collector-$USER
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/edge
                    operator: Exists
      containers:
        - image: isc-tutorial.hlrs.de/$USER/collector:latest
          name: collector
          imagePullPolicy: Always
          env:
            - name: BROKER_ADDRESS
              value: "mosquitto.isc25"
            - name: BROKER_PORT
              value: "1883"
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 200m
      imagePullSecrets:
        - name: tutorial-registry-secret
      restartPolicy: Always
      dnsPolicy: ClusterFirstWithHostNet
