apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-$USER
  namespace: decice
  labels:
    app: whisper-$USER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper-$USER
  template:
    metadata:
      labels:
        app: whisper-$USER
    spec:
      nodeSelector:
        kubernetes.io/hostname: isc-edge-01

      imagePullSecrets:
      - name: tutorial-registry-secret

      volumes:
#        - name: model-volume
#          emptyDir: {}
        - name: sound-dev
          hostPath:
            path: /dev/snd
#      initContainers:
#        - name: download-model
#          image: busybox:latest
#          command:
#            - sh
#            - -c
#            - >
#               sleep infinity
#              wget -O /models/ggml-base.bin 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium.bin'
#          volumeMounts:
#            - name: model-volume
#              mountPath: /models
      containers:
        - name: whisper
          image: "isc-tutorial.hlrs.de/$USER/whisper:321"
          imagePullPolicy: Always
          env:
            - name: MQTT_SERVER
              value: "mosquitto.isc25"
            - name: MQTT_PORT
              value: "1883"
            - name: MQTT_BUTTON_TOPIC
              value: "clock1/buttons"
            - name: MQTT_WHISPER_TOPIC
              value: "mic/stream"
            - name: WHISPER_DEVICE
              value: "0"
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
#            - name: model-volume
#              mountPath: /models
            - name: sound-dev
              mountPath: /dev/snd
